'use client'

import { useEffect, useState } from 'react'
import { Button } from '@/components/ui/button'
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { useToast } from '@/components/ui/toast'
import { formatCurrency, formatNumber, api } from '@/lib/utils'

interface Report {
  platform: string
  spend: number
  revenue: number
  conversions: number
}

interface Advice {
  title: string
  description: string
  severity: 'info' | 'warning' | 'opportunity' | 'alert'
  recommendedAction?: string
}

interface AdvisorResponse {
  advice: Advice[]
  source: 'llm' | 'rules'
  model?: string
}

export default function AdvisorPage() {
  const { toast } = useToast()
  const [reports, setReports] = useState<Report[]>([])
  const [campaignCount, setCampaignCount] = useState(0)
  const [advice, setAdvice] = useState<Advice[]>([])
  const [source, setSource] = useState<'llm' | 'rules' | null>(null)
  const [model, setModel] = useState<string | undefined>()
  const [loading, setLoading] = useState(true)
  const [refreshing, setRefreshing] = useState(false)

  useEffect(() => {
    loadAll()
  }, [])

  async function loadAll() {
    setLoading(true)
    try {
      const [advisorRes, reportsRes, campaignsRes] = await Promise.all([
        fetch(api('/api/advisor')),
        fetch(api('/api/reports')),
        fetch(api('/api/campaigns')),
      ])
      const advisor: AdvisorResponse = await advisorRes.json()
      const reportsData = await reportsRes.json()
      const campaignsData = await campaignsRes.json()

      if (Array.isArray(advisor.advice)) {
        setAdvice(advisor.advice)
        setSource(advisor.source)
        setModel(advisor.model)
      }
      setReports(Array.isArray(reportsData) ? reportsData : [])
      setCampaignCount(Array.isArray(campaignsData) ? campaignsData.length : 0)
    } catch (err) {
      toast({
        variant: 'error',
        title: 'Failed to load advisor',
        description: err instanceof Error ? err.message : undefined,
      })
    } finally {
      setLoading(false)
    }
  }

  async function refreshAdvice() {
    setRefreshing(true)
    try {
      const res = await fetch(api('/api/advisor'))
      const data: AdvisorResponse = await res.json()
      if (Array.isArray(data.advice)) {
        setAdvice(data.advice)
        setSource(data.source)
        setModel(data.model)
        toast({ variant: 'success', title: 'Advice refreshed' })
      }
    } catch (err) {
      toast({
        variant: 'error',
        title: 'Refresh failed',
        description: err instanceof Error ? err.message : undefined,
      })
    } finally {
      setRefreshing(false)
    }
  }

  const severityIcon: Record<Advice['severity'], string> = {
    alert: '🚨',
    warning: '⚠️',
    opportunity: '🚀',
    info: '💡',
  }

  const severityVariant: Record<
    Advice['severity'],
    'info' | 'warning' | 'success' | 'danger'
  > = {
    alert: 'danger',
    warning: 'warning',
    opportunity: 'success',
    info: 'info',
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64 text-gray-500">
        Loading advisor...
      </div>
    )
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">AI Advisor</h1>
          <p className="text-gray-500 text-sm mt-1">
            {source === 'llm'
              ? `Recommendations generated by ${model || 'Claude'} based on your last 7 days of performance.`
              : source === 'rules'
              ? 'Rule-based recommendations. Set ANTHROPIC_API_KEY to unlock LLM-generated advice.'
              : 'AI-powered optimization suggestions.'}
          </p>
        </div>
        <Button variant="outline" onClick={refreshAdvice} disabled={refreshing}>
          {refreshing ? 'Refreshing…' : 'Refresh Advice'}
        </Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="p-5 text-center">
          <p className="text-3xl font-bold">{campaignCount}</p>
          <p className="text-sm text-gray-500 mt-1">Total Campaigns</p>
        </Card>
        <Card className="p-5 text-center">
          <p className="text-3xl font-bold">{formatCurrency(reports.reduce((s, r) => s + (r.spend || 0), 0))}</p>
          <p className="text-sm text-gray-500 mt-1">Total Spend</p>
        </Card>
        <Card className="p-5 text-center">
          <p className="text-3xl font-bold">{formatNumber(reports.reduce((s, r) => s + (r.conversions || 0), 0))}</p>
          <p className="text-sm text-gray-500 mt-1">Total Conversions</p>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>
            Recommendations ({advice.length})
            {source === 'llm' && (
              <Badge variant="info" className="ml-2 align-middle">AI</Badge>
            )}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="space-y-4">
            {advice.map((a, i) => (
              <div key={i} className="border rounded-lg p-4">
                <div className="flex items-start gap-3">
                  <span className="text-xl mt-0.5">{severityIcon[a.severity] || '💡'}</span>
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1 flex-wrap">
                      <h3 className="font-semibold text-sm">{a.title}</h3>
                      <Badge variant={severityVariant[a.severity] || 'info'}>
                        {a.severity}
                      </Badge>
                    </div>
                    <p className="text-sm text-gray-600">{a.description}</p>
                    {a.recommendedAction && (
                      <p className="text-sm text-blue-700 mt-2 flex items-start gap-1.5">
                        <span>→</span>
                        <span>{a.recommendedAction}</span>
                      </p>
                    )}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  )
}
